### ISSUE TITLE
Device not allowed

### ISSUE THREAD

**Issue by vicdilou** [ItayXD/MMM-Admin-Interface#1]
Hi,
When I go to "<HOST>:8080/MMM-Admin-Interface/" I have this message : 

This device is not allowed to access your mirror. 
Please check your config.js or config.js.sample to change this.

I have to add my IP ?
How can I do this ?

**Comment by ItayXD** [comment]
Fixed, check the new readme.
Hint: try adding `ipWhitelist: ["192.168.X.1/24 , ::ffff:192.168.X.1/24"],` to you config.js
